### ISSUE TITLE
micropub-android: Missing element "scope" in authorization_endpoint response

### ISSUE THREAD

**Issue by cweiske** [cweiske/anoweco#10]
When trying to login to commentpara.de with https://github.com/pstuifzand/micropub-android I get an error:

```
04-23 18:20:50.507 12647 12647 E micropub: android.accounts.AuthenticatorException: Could not verify authorization: Missing element "scope" in authorization_endpoint response
04-23 18:20:50.507 12647 12647 E micropub: 	at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2245)
04-23 18:20:50.507 12647 12647 E micropub: 	at android.accounts.AccountManager.-wrap0(AccountManager.java)
04-23 18:20:50.507 12647 12647 E micropub: 	at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2081)
04-23 18:20:50.507 12647 12647 E micropub: 	at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
04-23 18:20:50.507 12647 12647 E micropub: 	at android.os.Binder.execTransact(Binder.java:565)
```

It posts to `https://commentpara.de/auth.php`:

```
code=ZW1vamk9JTVDMzYwJTVDMjM3JTVDMjIyJTVDMjUxJm1lPWh0dHBzJTNBJTJGJTJGY29tbWVudHBhcmEuZGUlMkZ1c2VyJTJGMy5odG0mc2NvcGU9Y3JlYXRlK2VkaXQrdXBkYXRlK3Bvc3QrZGVsZXRlJnNpZ25hdHVyZT1GSVhNRQ%3D%3D
&redirect_uri=wrimini%3A%2F%2Foauth
&client_id=https%3A%2F%2Fstuifzand.eu%2Fmicropub
```

and gets in return:

```
{"me":"https:\/\/commentpara.de\/user\/3.htm"}
```

**Comment by cweiske** [comment]
Upstream issue: https://github.com/pstuifzand/micropub-android/issues/14
